trigger:
  batch: true
  branches:
    include: [master]

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: Release

steps:
- script: |
    az login --service-principal --username $(AZ_SP_ID) --password $AZ_SP_PASSWORD --tenant $(AZ_SP_TENANT_ID)
    az aks install-cli
    az aks get-credentials -g $(AZ_RESOURCE_GROUP) -n $(AZ_AKS_CLUSTER_NAME)
  env:
    AZ_SP_PASSWORD: $(AZ_SP_PASSWORD)
  displayName: Login with Azure CLI
- script: |
    curl https://s3.amazonaws.com/datawire-static-files/forge/$(curl https://s3.amazonaws.com/datawire-static-files/forge/latest.url)/forge -o /tmp/forge
    chmod a+x /tmp/forge
    sudo mv /tmp/forge /usr/local/bin
  displayName: Install forge binary
- script: |
    echo "# Global forge configuration" >> ./forge.yaml
    echo "# DO NOT CHECK INTO GITHUB, THIS FILE CONTAINS SECRETS" >> ./forge.yaml
    echo "registry:" >> ./forge.yaml
    echo "  type: docker" >> ./forge.yaml
    echo "  url: $AZ_ACR_ACCOUNT.azurecr.io" >> ./forge.yaml
    echo "  user: $AZ_ACR_ACCOUNT" >> ./forge.yaml
    echo -n "  password: " >> ./forge.yaml
    printf $AZ_ACR_PASSWORD | base64 >> ./forge.yaml
    echo "  namespace: $AZ_ACR_ACCOUNT" >> ./forge.yaml
  env:
    AZ_ACR_ACCOUNT: $(AZ_ACR_ACCOUNT) 
    AZ_ACR_PASSWORD: $(AZ_ACR_PASSWORD)
  displayName: Write forge configuration
- script: |
    python3 write_env.py
  env:
    AZURE_SEARCH_ACCOUNT_NAME: $(AZURE_SEARCH_ACCOUNT_NAME)
    AZURE_SEARCH_KEY: $(AZURE_SEARCH_KEY)
  displayName: Write Config
- script: |
    forge --profile stable build
  displayName: Build image with forge
- script: |
    DOCKER_IMAGE=$(docker images -q | sed 1q)
    docker run -i "$DOCKER_IMAGE" /bin/sh -c "black /usr/src"
  displayName: Lint with black
  continueOnError: true
- script: |
    DOCKER_IMAGE=$(docker images -q | sed 1q)
    docker run -i -v junit:/usr/src "$DOCKER_IMAGE" /bin/sh -c "pytest src/app/tests --doctest-modules --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html"
  displayName: Test with pytest
- script: |
    forge --profile stable deploy
  displayName: Deploy to $(AZ_AKS_CLUSTER_NAME) cluster
