name: ccg

profiles:
  stable:
    endpoint: /ccg/
    max_memory: 0.5G
    max_cpu: 0.5
  canary:
    endpoint: /ccg/
    weight: 10 # percentage of traffic to route to this class of deployment
    max_memory: 0.25G
    max_cpu: 0.25
max_cpu: 0.25